# -*- coding: utf-8 -*-
"""Cópia de app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4Ts0adnAY3vEI2aEH2bWK1-zPjlJjBV

Assstente IA -Chatbot https://github.com/streamlit/demo-ai-assistant

Dashboard Estoque https://github.com/64squaresapexllp/snowflake_health

Chatbot https://github.com/streamlit/llm-examples

Analise de algo https://github.com/tylerjrichards/streamlit_goodreads_app

# **Banco de Dados - Não Relacional**
### **Pontifícia Universidade Católica de Campinas**
### **Prof. Felipe Cavalaro**
### **Integrantes**
- Alice Pasolini - 25012938
- Enzo Guerra - 25007153
- Guilherme Cintra - 25004996
- Julia Leandro - 25009148
- Lavínia Oliveira - 25894981

---
## **ODS 4 - Educação e Qualidade**
#### Indicadores escolhidos:
- Proficiência do Sistema de Avaliação de Rendimento Escolar do Estado de São Paulo (SARESP) por município
- Fluxo escolar por município
- Ausências por servidor (Faltas e absenteísmo)

Fontes dos datasets(respectivamente)
- https://dados.educacao.sp.gov.br/dataset/profici%C3%AAncia-do-sistema-de-avalia%C3%A7%C3%A3o-de-rendimento-escolar-do-estado-de-s%C3%A3o-paulo-saresp-4
- https://dados.educacao.sp.gov.br/dataset/fluxo-escolar-por-munic%C3%ADpio
- https://dados.educacao.sp.gov.br/dataset/aus%C3%AAncias-por-servidor

---
## **🖥️ | IMPLEMENTAÇÃO: ELT** (Extract, Load, Transform)

### **Estrutura Base**
- Bibliotecas e pacotes
- Funções
- Variáveis globais
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/tylerjrichards/streamlit_goodreads_app
# %cd streamlit_goodreads_app
!pip install streamlit -q

"""pymongo"""

!pip install pandas pymongo -q

"""### Streamlit Dashboard"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# 
# st.title('Uber pickups in NYC')
# 
# DATE_COLUMN = 'date/time'
# DATA_URL = ('https://s3-us-west-2.amazonaws.com/'
#             'streamlit-demo-data/uber-raw-data-sep14.csv.gz')
# 
# @st.cache_data
# def load_data(nrows):
#     data = pd.read_csv(DATA_URL, nrows=nrows)
#     lowercase = lambda x: str(x).lower()
#     data.rename(lowercase, axis='columns', inplace=True)
#     data[DATE_COLUMN] = pd.to_datetime(data[DATE_COLUMN])
#     return data
# 
# data_load_state = st.text('Loading data...')
# data = load_data(10000)
# data_load_state.text("Done! (using st.cache_data)")
# 
# if st.checkbox('Show raw data'):
#     st.subheader('Raw data')
#     st.write(data)
# 
# st.subheader('Number of pickups by hour')
# hist_values = np.histogram(data[DATE_COLUMN].dt.hour, bins=24, range=(0,24))[0]
# st.bar_chart(hist_values)
# 
# # Some number in the range 0-23
# hour_to_filter = st.slider('hour', 0, 23, 17)
# filtered_data = data[data[DATE_COLUMN].dt.hour == hour_to_filter]
# 
# st.subheader('Map of all pickups at %s:00' % hour_to_filter)
# st.map(filtered_data)

with open("requirements.txt", "r") as f:
    content = f.read()

content = content.replace("numpy==1.23.5", "numpy>=1.26")

with open("requirements.txt", "w") as f:
    f.write(content)

!pip install -r requirements.txt -q
!npm install localtunnel -q

!curl ipv4.icanhazip.com

!streamlit run app.py &>/dev/null&
!npx localtunnel --port 8501

"""### Funções e estruturas genéricas para a leitura dos Datasets

URL Base - GitHub
"""

URLsaresp = "https://raw.githubusercontent.com/leasju/pi_educacao_qualidade/main/Proficiencia%20do%20SARESP"
URLfluxo = "https://raw.githubusercontent.com/leasju/pi_educacao_qualidade/main/Fluxo%20Escolar"
URLausencia = "https://raw.githubusercontent.com/leasju/pi_educacao_qualidade/main/Ausencia"

"""Configuração dos anos nos Datasets"""

# Dicionário com os anos
dict_ano = {
    22: 2022,
    23: 2023,
    24: 2024
}

# Adiciona a coluna 'Ano' aos datasets
def add_col(df, ano):
    df["Ano"] = ano
    return df

"""Função que realiza a leitura dos Datasets e os concatena ao final"""

def le_dataset(base_url, links):
    lista_dfs = []

    for k, v in links.items():

        # Detecta formato do dicionário
        # ano : {"nome_arquivo"}
        if isinstance(k, int):
            ano = k
            nome = v
        # "nome_arquivo" : ano
        else:
            nome = k
            ano = v

        nome_encoded = quote(nome)
        url = f"{base_url}/{nome_encoded}"

        df = None

        for enc in ['utf-8-sig', 'latin-1']:
            try:
                # print(f"Tentando: {url}")
                df = pd.read_csv(url, sep=';', encoding=enc)
                # print(f"OK: {nome}")
                break
            except Exception as e:
                # print(f"ERRO: {nome} | {e}")
                continue

        if df is not None:
            for chave in dict_ano:
                if str(chave) in nome:
                    df = add_col(df, dict_ano[chave])
                    break
            df.columns = df.columns.str.upper()
            lista_dfs.append(df)
        time.sleep(2)

    return pd.concat(lista_dfs, ignore_index=True)

"""Lista da região metropolitana de Campinas (10 principais municípios)"""

regiaoCampinas = ['CAMPINAS','HORTOLANDIA','SUMARE','INDAIATUBA','PAULINIA','AMERICANA','VALINHOS','VINHEDO','ITATIBA','SANTA BARBARA D\'OESTE']

"""### **DATASET SARESP**

Leitura e análise do dataframe
"""

sarespLinks = {
    2022: "Proficiencia do SARESP por municipio de 2022_0.csv",
    2023: "Proficiencia do SARESP por Municipio de 2023_0.csv",
    2024: "Proficiencia do SARESP por Municipio de 2024_0.csv"
}

print(sarespLinks)

sarespDF = le_dataset(URLsaresp, sarespLinks)
sarespDF

# Cópia do dataframe original (Caso precise)
sarespDFOriginal = sarespDF.copy()
sarespDFOriginal

"""Normalização do dataframe"""

apagarCol = ['DEPADM','DEPBOL','CODRMET','CODMUN','COD_PER','CO_COMP']
sarespDFR = sarespDF.drop(columns=apagarCol)
sarespDFR.head().style.hide(axis="index")

sarespDFR = sarespDFR[sarespDFR.MUN.isin(regiaoCampinas)]

sarespDFR = sarespDFR.reset_index(drop=True)
sarespDFR = sarespDFR.rename(columns={
    'MUN': 'MUNICÍPIOS',
    'DS_COMP': 'COMPETÊNCIA',
    'MEDPROF': 'MÉDIA_PROFICIÊNCIA',
    'NOMEDEPBOL': 'REDE',
})
sarespDFR

"""Download"""

sarespDFR.to_csv('sarespDF.csv', index=False)

"""#### (PARTE DO ENZO) Gráficos"""

'''
# Cálculo dos limites para tratar os outliers
Q1 = sarespDFR['MÉDIA_PROFICIÊNCIA'].quantile(0.25)

Q3 = sarespDFR['MÉDIA_PROFICIÊNCIA'].quantile(0.75)
IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# -----------------------------------

plt.figure(figsize=(10, 6))
sns.boxplot(data=sarespDFR, x=sarespDFR.MUNICÍPIOS, y=sarespDFR.MÉDIA_PROFICIÊNCIA, hue=sarespDFR["MUNICÍPIOS"])
plt.title("Média de proficiência por município")
plt.xticks(fontsize=8, rotation=30)
plt.xlabel("Municípios")
plt.ylabel("Média de Proficiência")
plt.ylim(limite_inferior,limite_superior)
plt.show()
'''



"""### **DATASET FLUXO ESCOLAR DOS ALUNOS**
Aprovação e Reprovação

Leitura dos datasets
"""

fluxoLinks = {
    2022: "Fluxo Escolar 2022 - por municipio.csv",
    2023: "Fluxo Escolar 2023 - por município.csv",
    2024: "Fluxo Escolar 2024 - por municipio.csv"
}

fluxoDF = le_dataset(URLfluxo, fluxoLinks)
print("Anos carregados:", fluxoDF['ANO_REF'].unique() if 'ANO_REF' in fluxoDF.columns else 'Erro ao carregar')
fluxoDF

# Cópia do dataframe original(Caso precise)
fluxoDFOriginal = fluxoDF.copy()
fluxoDFOriginal

"""Normalização do dataframe"""

count = 0
# Mantemos a coluna 'ANO' (ou 'ANO_REF') fora da lista de exclusão
apagarCol = ['ANO_LETIVO','NM_DIRETORIA','CD_REDE_ENSINO','ABA_1','ABA_2']

# Percorre as colunas para adicionar as que possuam o número 3 no final (Ensino médio)
for i in fluxoDF.columns:
  if fluxoDF.columns[count][-1] == '3':
    apagarCol.append(i)
  count += 1

# Apaga as colunas da lista apagarCol
fluxoDFR = fluxoDF.drop(columns=apagarCol)

"""Renomeação das colunas"""

fluxoDFR = fluxoDFR.rename(columns={
    'NM_MUNICIPIO': 'MUNICÍPIOS',
    'APR_1': 'APROVAÇÃO ANOS INICIAIS 9 ANOS',
    'APR_2': 'APROVAÇÃO ANOS FINAIS 9 ANOS',
    'REP_1': 'REPROVAÇÃO ANOS INICIAIS 9 ANOS',
    'REP_2': 'REPROVAÇÃO ANOS FINAIS 9 ANOS'
})
fluxoDFR.columns

"""Conversões"""

# Função auxiliar para converter strings com vírgula para float
def clean_and_convert(df, columns):
    for col in columns:
        if col in df.columns:
            # Converte para string, remove espaços, troca vírgula por ponto e converte para float
            df[col] = pd.to_numeric(df[col].astype(str).str.replace(',', '.').str.strip(), errors='coerce')
    return df

# 1. Convertendo colunas do Fluxo Escolar
cols_fluxo = ['APROVAÇÃO ANOS INICIAIS 9 ANOS', 'REPROVAÇÃO ANOS INICIAIS 9 ANOS',
              'APROVAÇÃO ANOS FINAIS 9 ANOS', 'REPROVAÇÃO ANOS FINAIS 9 ANOS']
if 'fluxoDFR' in globals():
    fluxoDFR = clean_and_convert(fluxoDFR, cols_fluxo)
    print("Colunas de fluxoDFR convertidas.")

# 2. Convertendo colunas do SARESP
if 'sarespDFR' in globals():
    sarespDFR = clean_and_convert(sarespDFR, ['MÉDIA_PROFICIÊNCIA'])
    print("Colunas de sarespDFR convertidas.")

display(fluxoDFR.head())

"""Transformação das colunas e exibição apenas das necessárias para análise"""

fluxoDFR = fluxoDFR[fluxoDFR.MUNICÍPIOS.isin(regiaoCampinas)]
fluxoDFR = fluxoDFR.reset_index(drop=True)
colunasAgrupadas = ['MUNICÍPIOS','ANO']
colunasMedia = ['APROVAÇÃO ANOS INICIAIS 9 ANOS', 'REPROVAÇÃO ANOS INICIAIS 9 ANOS', 'APROVAÇÃO ANOS FINAIS 9 ANOS', 'REPROVAÇÃO ANOS FINAIS 9 ANOS']
fluxoDFR = fluxoDFR.groupby(colunasAgrupadas)[colunasMedia].mean().reset_index()
fluxoDFR

"""Download"""

#Download do dataset unificado e normalizado
fluxoDFR.to_csv('fluxoDF.csv', index=False)

"""### **DATASET AUSÊNCIAS DOS PROFESSORES**

Leitura dos datasets
"""

ausLinks = {
    "BASE_AUSENCIAS_FINAL_1124.csv": 2024,
    "BASE_AUSENCIAS_FINAL_1224.csv": 2024,
    "[BASE_AUSENCIAS_FINAL_1024].csv": 2024,
    "[DBO].[BASE_AUSENCIAS_0724].csv": 2024,
    "[dbo].[BASE_AUSENCIAS_0124].csv": 2024,
    "[dbo].[BASE_AUSENCIAS_0224].csv": 2024,
    "[dbo].[BASE_AUSENCIAS_0324].csv": 2024,
    "[dbo].[BASE_AUSENCIAS_0424].csv": 2024,
    "[dbo].[BASE_AUSENCIAS_0524].csv": 2024,
    "[dbo].[BASE_AUSENCIAS_0624].csv": 2024,
    "[dbo].[BASE_AUSENCIAS_0824].csv": 2024,
    "[dbo].[BASE_AUSENCIAS_0924].csv": 2024,

    "[dbo].[BASE_AUSENCIAS_0123].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_0223].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_0323].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_0423].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_0523].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_0623].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_0723].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_0823].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_0923].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_1023].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_1123].csv": 2023,
    "[dbo].[BASE_AUSENCIAS_1223].csv": 2023,

    "[dbo].[BASE_AUSENCIAS_0122].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_0222].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_0322].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_0422].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_0522].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_0622].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_0722].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_0822].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_0922].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_1022].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_1122].csv": 2022,
    "[dbo].[BASE_AUSENCIAS_1222].csv": 2022
}

ausDF = le_dataset(URLausencia, ausLinks)
ausDF

# Cópia do dataframe original(Caso precise)
ausDFOriginal = ausDF.copy()
ausDFOriginal

"""Normalização do dataframe"""

# Apaga as colunas dentro da lista apagarCol
apagarCol = ['REGIAO_EXERC', 'DE_EXERC', 'NOME_UA_EXERC', 'NOME_CARGO_EXERC', 'CIE_ESCOLA', 'UA_EXERC', 'DI', 'CARGO_EXERC', 'CATEG_E']
ausDFR = ausDFOriginal.drop(columns=apagarCol)

# Normaliza todos os municípios dentro da coluna para que não haja espaços vazios e todos sejam maiúsculos
ausDFR['MUNICIPIO_EXERC'] = ausDFR['MUNICIPIO_EXERC'].str.strip().str.upper()

# Seleciona apenas os municípios da região de Campinas
ausDFR = ausDFR[ausDFR['MUNICIPIO_EXERC'].isin(regiaoCampinas)]

ausDFR = ausDFR.rename(columns={
    'MUNICIPIO_EXERC': 'MUNICÍPIOS',
    'TT_DIAS_FALTA_JUST': 'TOTAL FALTAS JUST',
    'TT_DIAS_FALTA_INJUST': 'TOTAL FALTAS INJUST',
})

ausDFR['TOTAL DIAS AUSENTES'] = (ausDFR['TOTAL FALTAS JUST'] + ausDFR['TOTAL FALTAS INJUST'])

ausDFR = (ausDFR.groupby('MUNICÍPIOS')[['TOTAL FALTAS JUST','TOTAL FALTAS INJUST', 'TOTAL DIAS AUSENTES']].sum().reset_index())

ausDFR

"""Download"""

ausDFR.to_csv('ausDF.csv', index=False)

"""---
## **📊 | ANÁLISE EXPLORATÓRIA**

Agrupando os municípios pela média por série/ano
"""

sarespDFILTROR = sarespDFR.drop(columns=['PERIODO'])
sarespDFILTROR.groupby(["MÉDIA_PROFICIÊNCIA","MUNICÍPIOS"]).sum()
sarespDFILTROR

"""---
## **📊 | GRAFOS**
"""

